// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiProject.Data;

#nullable disable

namespace RestApiProject.Migrations
{
    [DbContext(typeof(RestDbContext))]
    [Migration("20250807183444_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestApiProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "kamal",
                            Title = "The Great Gatsby",
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 2,
                            Author = "perera",
                            Title = "To kill a mockingbird",
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 3,
                            Author = "sunil",
                            Title = "1949",
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 4,
                            Author = "harper",
                            Title = "express",
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 5,
                            Author = "harper",
                            Title = "victory",
                            YearPublished = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
